# Generated by Django 3.2.25 on 2025-03-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender_username', models.CharField(max_length=100)),
                ('reporter_username', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('neutral', 'Neutral'), ('bad', 'Bad'), ('offensive', 'Offensive')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
