# Generated by Django 3.2.25 on 2025-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxicity_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('report_type', models.IntegerField(choices=[(0, 'Hate Speech'), (1, 'Offensive Language'), (2, 'Not Toxic (False Positive)')])),
                ('reporter_username', models.CharField(max_length=100)),
                ('reported_username', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ReportedMessage',
        ),
    ]
